import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Images } from "@/constants";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MAUI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="icon"
        href="/icon?<generated>"
        type="image/<generated>"
        sizes="<generated>"
      />
      <body className={inter.className}>
        {/* navbar section */}
        <div className="flex justify-between place-items-start sm:h-auto h-[25rem] gap-3 sm:bg-black top-0 fixed w-full z-[100]">
          <Link href='/' className="pl-[1.5rem] pt-3 sm:pl-[4rem] sm:pt-[4rem] w-auto h-auto bg-black p-3">
            <Image src={Images.logo} alt="logo" priority={true} width={200} />
          </Link>

          <Navbar />
        </div>
        <div className="sm:mt-[10rem] mt-[25rem]">
          {children}
        </div>
      </body>
    </html>
  );
}
